# Generated by Django 4.1.5 on 2023-01-24 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square', models.CharField(max_length=50, verbose_name='Жилая площадь квартиры (кв.м.)')),
                ('kitchen_square', models.CharField(max_length=50, verbose_name='Площадь кухни (кв.м)')),
                ('balcony_square', models.CharField(max_length=50, verbose_name='Площадь балкона, если есть (кв.м) (По умолчанию: нет)')),
                ('price', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Цена квартиры')),
                ('price_punctuation', models.CharField(max_length=10, verbose_name='Валюта (По умолчанию: ₽)')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес квартиры')),
                ('underground', models.CharField(max_length=255, verbose_name='Ближайшее метро')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landing.apartment', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Фото квартиры',
                'verbose_name_plural': 'Фото квартиры',
            },
        ),
    ]
