# Generated by Django 4.1.5 on 2023-01-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentphotos',
            name='apartment',
        ),
        migrations.AddField(
            model_name='apartment',
            name='photos',
            field=models.ManyToManyField(null=True, to='landing.apartmentphotos'),
        ),
    ]
